# Generated by Django 3.2.13 on 2022-12-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('uri', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('cover_image', models.CharField(max_length=150)),
                ('release_date', models.DateField()),
            ],
            options={
                'db_table': 'backend_api_album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('uri', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150, null=True)),
                ('image', models.CharField(max_length=150, null=True)),
                ('popularity', models.FloatField()),
            ],
            options={
                'db_table': 'backend_api_artist',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'backend_api_genre',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('num_followers', models.IntegerField()),
            ],
            options={
                'db_table': 'backend_api_playlist',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('uri', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('loudness', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.FloatField()),
                ('time_signature', models.FloatField()),
                ('camelot_key', models.CharField(max_length=3)),
                ('popularity', models.FloatField()),
                ('explicit', models.IntegerField()),
                ('preview_url', models.CharField(blank=True, max_length=250, null=True)),
                ('spotify_url', models.CharField(max_length=250)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.album')),
            ],
            options={
                'db_table': 'backend_api_track',
            },
        ),
        migrations.CreateModel(
            name='TrackArtists',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.track')),
            ],
            options={
                'db_table': 'backend_api_track_artists',
                'unique_together': {('track', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistTracks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.track')),
            ],
            options={
                'db_table': 'backend_api_playlist_tracks',
                'unique_together': {('playlist', 'track')},
            },
        ),
        migrations.CreateModel(
            name='ArtistGenres',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.genre')),
            ],
            options={
                'db_table': 'backend_api_artist_genres',
                'unique_together': {('artist', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='AlbumArtists',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.artist')),
            ],
            options={
                'db_table': 'backend_api_album_artists',
                'unique_together': {('album', 'artist')},
            },
        ),
    ]
