# Generated by Django 3.2.13 on 2022-10-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongID', models.IntegerField()),
                ('Artist', models.CharField(max_length=255)),
                ('SongKey', models.CharField(max_length=255)),
            ],
        ),
    ]
