# Generated by Django 3.2.13 on 2022-10-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='SongKey',
            new_name='songKey',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='SongID',
        ),
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
