# Generated by Django 3.2.13 on 2022-12-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artistgenres',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='artistgenres',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistgenres',
            name='genre',
        ),
        migrations.AlterUniqueTogether(
            name='playlisttracks',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playlisttracks',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlisttracks',
            name='track',
        ),
        migrations.AlterUniqueTogether(
            name='trackartists',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trackartists',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='trackartists',
            name='track',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='backend_api.Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='backend_api.Genre'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='backend_api.Track'),
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(to='backend_api.Artist'),
        ),
        migrations.DeleteModel(
            name='AlbumArtists',
        ),
        migrations.DeleteModel(
            name='ArtistGenres',
        ),
        migrations.DeleteModel(
            name='PlaylistTracks',
        ),
        migrations.DeleteModel(
            name='TrackArtists',
        ),
    ]
