# Generated by Django 3.2.13 on 2022-12-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_track_explicit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
