# Generated by Django 3.2.13 on 2022-10-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20221027_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='tempo',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
