# Generated by Django 3.2.13 on 2022-12-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_playlist_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='uri',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
