# Generated by Django 3.2.13 on 2022-12-07 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_playlist_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('track_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_api.track')),
                ('queue', models.IntegerField()),
            ],
            options={
                'db_table': 'backend_api_priority',
            },
            bases=('backend_api.track',),
        ),
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_tempo', models.FloatField()),
                ('cam_tempo_dance', models.FloatField()),
                ('cam_tempo_dance_energy', models.FloatField()),
                ('cam_tempo_dance_energy_loud', models.FloatField()),
                ('all_dist', models.FloatField()),
                ('from_uri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_uri', to='backend_api.priority')),
                ('to_uri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_uri', to='backend_api.priority')),
            ],
            options={
                'db_table': 'backend_api_similar',
            },
        ),
        migrations.AddField(
            model_name='priority',
            name='similar_track',
            field=models.ManyToManyField(related_name='_backend_api_priority_similar_track_+', through='backend_api.Similar', to='backend_api.Priority'),
        ),
    ]
