# Generated by Django 3.2.13 on 2022-11-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_tracks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
    ]
