# Generated by Django 3.2.13 on 2022-12-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_auto_20221207_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similar',
            old_name='cam_tempo',
            new_name='cam_dance',
        ),
        migrations.RenameField(
            model_name='similar',
            old_name='cam_tempo_dance',
            new_name='cam_dance_energy',
        ),
        migrations.RenameField(
            model_name='similar',
            old_name='cam_tempo_dance_energy',
            new_name='cam_dance_energy_valence',
        ),
        migrations.RenameField(
            model_name='similar',
            old_name='cam_tempo_dance_energy_loud',
            new_name='cam_dance_energy_valence_acoustic',
        ),
    ]
