# Generated by Django 3.2.13 on 2022-11-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_rename_tracks_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_url',
            field=models.CharField(max_length=250),
        ),
    ]
