# Generated by Django 3.2.13 on 2022-12-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20221210_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similar',
            name='from_uri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_uri', to='backend_api.priority'),
        ),
        migrations.AlterField(
            model_name='similar',
            name='to_uri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_uri', to='backend_api.priority'),
        ),
    ]
