# Generated by Django 3.2.13 on 2022-11-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20221101_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='camelot_key',
            field=models.CharField(max_length=2),
        ),
    ]
