# Generated by Django 3.2.13 on 2022-11-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_alter_track_camelot_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='acousticness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='danceability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='instrumental',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='liveness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='loudness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='popularity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='speechiness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='time_signature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='valance',
            field=models.FloatField(),
        ),
    ]
