# Generated by Django 3.2.13 on 2022-11-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_auto_20221101_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='valance',
            new_name='valence',
        ),
    ]
