# Generated by Django 3.2.13 on 2022-11-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_rename_valance_track_valence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='instrumental',
            new_name='instrumentalness',
        ),
    ]
