# Generated by Django 3.2.13 on 2022-11-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_rename_instrumental_track_instrumentalness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='camelot_key',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
