# Generated by Django 3.2.13 on 2022-11-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_alter_track_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
