# Generated by Django 3.2.13 on 2022-11-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0014_auto_20221101_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='songs',
            new_name='artists',
        ),
    ]
